spring:
  datasource:
    url: jdbc:h2:tcp://localhost/~/askme
    username: sa
    password: 1q2w3e4r
    driver-class-name: org.h2.Driver

  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        format_sql: true

logging:
  level:
    org.hibernate:
    sql: debug
    type : trace
